/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scofd_gentemplate_FastConverJNI */

#ifndef _Included_com_scofd_gentemplate_FastConverJNI
#define _Included_com_scofd_gentemplate_FastConverJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scofd_gentemplate_FastConverJNI
 * Method:    initConverter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_scofd_gentemplate_FastConverJNI_initConverter
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_scofd_gentemplate_FastConverJNI
 * Method:    finalizeConverter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scofd_gentemplate_FastConverJNI_finalizeConverter
  (JNIEnv *, jobject);

/*
 * Class:     com_scofd_gentemplate_FastConverJNI
 * Method:    convert
 * Signature: (Ljava/lang/String;[B[BLjava/util/ArrayList;Ljava/util/ArrayList;J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_scofd_gentemplate_FastConverJNI_convert
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
