.PHONY:compile run clean
 
compile:
	javac com/scofd/gentemplate/FastConverJNI.java com/scofd/gentemplate/model/*.java
run:
	java -Djava.library.path=../lib com.scofd.gentemplate.FastConverJNI
 
clean:
	@echo "start clean"
